# Generated by Django 4.0.4 on 2022-06-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop_notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('disco', models.CharField(max_length=20)),
                ('memoria', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
