# Generated by Django 4.0.4 on 2022-06-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_desktop_notebook_options_alter_monitor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop_notebook',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='monitor',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='periferico',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
